//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAbonent
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public int AbonentId { get; set; }
        public System.DateTime DateOfReceiving { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Abonent Abonent { get; set; }
        public virtual Book Book { get; set; }
    }
}
