//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibraryRusTelekonEntities : DbContext
    {
        public LibraryRusTelekonEntities()
            : base("name=LibraryRusTelekonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent> Abonent { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookAbonent> BookAbonent { get; set; }
        public virtual DbSet<BookAuthor> BookAuthor { get; set; }
        public virtual DbSet<BookDomain> BookDomain { get; set; }
        public virtual DbSet<Domain> Domain { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
    
        public virtual ObjectResult<BookPopularityReport_Result> BookPopularityReport(Nullable<System.DateTime> firstDate, Nullable<System.DateTime> lastDate)
        {
            var firstDateParameter = firstDate.HasValue ?
                new ObjectParameter("firstDate", firstDate) :
                new ObjectParameter("firstDate", typeof(System.DateTime));
    
            var lastDateParameter = lastDate.HasValue ?
                new ObjectParameter("lastDate", lastDate) :
                new ObjectParameter("lastDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BookPopularityReport_Result>("BookPopularityReport", firstDateParameter, lastDateParameter);
        }
    }
}
